# Generated by Django 5.2.7 on 2025-12-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_skill_category_skill_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='platform',
            field=models.CharField(choices=[('udemy', 'Udemy'), ('youtube', 'YouTube'), ('coursera', 'Coursera'), ('edx', 'edX'), ('pluralsight', 'Pluralsight'), ('linkedin_learning', 'LinkedIn Learning'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('video', 'Video'), ('course', 'Course'), ('article', 'Article'), ('book', 'Book'), ('tutorial', 'Tutorial'), ('other', 'Other')], max_length=20),
        ),
    ]
