# Generated by Django 5.2.7 on 2025-12-14 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_resource_description_alter_resource_platform_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'ordering': ['-assigned_at']},
        ),
    ]
